<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../BuildingBlock.Api/BuildingBlock.Api.csproj" />
    <ProjectReference Include="../BuildingBlock.Application/BuildingBlock.Application.csproj" />
    <ProjectReference Include="../BuildingBlock.Domain/BuildingBlock.Domain.csproj" />
    <ProjectReference Include="../BuildingBlock.Infrastructure/BuildingBlock.Infrastructure.csproj" />
    <ProjectReference Include="../BuildingBlock.Infrastructure.EntityFrameworkCore.SqlServer/BuildingBlock.Infrastructure.EntityFrameworkCore.SqlServer.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" />
    <PackageReference Include="NetArchTest.Rules" />
    <PackageReference Include="Testcontainers.MsSql" />
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
