// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wasla.Infrastructure.EntityFrameworkCore.SqlServer.Persistence;

#nullable disable

namespace Wasla.Infrastructure.EntityFrameworkCore.SqlServer.Persistence.Migrations
{
    [DbContext(typeof(WaslaDbContext))]
    [Migration("20260908093258_AddDoctorSpecializationsAndPracticeLocation")]
    partial class AddDoctorSpecializationsAndPracticeLocation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Wasla.Domain.Doctors.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<Guid?>("ApprovedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NationalId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PersonalIdBackMediaKey")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PersonalIdFrontMediaKey")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ProfileImageMediaKey")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("ReactivatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReactivatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("RejectedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RejectedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid?>("SuspendedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("SuspendedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SuspensionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SyndicateCardBackMediaKey")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SyndicateCardFrontMediaKey")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique()
                        .HasDatabaseName("UX_Doctors_ApplicationUserId");

                    b.HasIndex("ApprovalStatus")
                        .HasDatabaseName("IX_Doctors_ApprovalStatus");

                    b.HasIndex("ApprovedByApplicationUserId");

                    b.HasIndex("CreatedOnUtc")
                        .HasDatabaseName("IX_Doctors_CreatedOnUtc");

                    b.HasIndex("NationalId")
                        .IsUnique()
                        .HasDatabaseName("UX_Doctors_NationalId")
                        .HasFilter("[NationalId] IS NOT NULL");

                    b.HasIndex("ReactivatedByApplicationUserId");

                    b.HasIndex("RejectedByApplicationUserId");

                    b.HasIndex("SuspendedByApplicationUserId");

                    b.ToTable("Doctors", (string)null);
                });

            modelBuilder.Entity("Wasla.Domain.Doctors.DoctorPracticeLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DetailedAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GovernorateId")
                        .HasColumnType("int");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("CityId");

                    b.HasIndex("DoctorId")
                        .IsUnique()
                        .HasDatabaseName("UX_DoctorPracticeLocations_DoctorId");

                    b.HasIndex("GovernorateId");

                    b.ToTable("DoctorPracticeLocations", null, t =>
                        {
                        });
                });

            modelBuilder.Entity("Wasla.Domain.Doctors.DoctorSpecialization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<Guid>("MedicalSpecializationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByApplicationUserId");

                    b.HasIndex("DoctorId")
                        .IsUnique()
                        .HasDatabaseName("UX_DoctorSpecializations_OnePrimaryPerDoctor")
                        .HasFilter("[IsPrimary] = 1");

                    b.HasIndex("MedicalSpecializationId");

                    b.HasIndex("DoctorId", "MedicalSpecializationId")
                        .IsUnique()
                        .HasDatabaseName("UX_DoctorSpecializations_DoctorId_MedicalSpecializationId");

                    b.ToTable("DoctorSpecializations", (string)null);
                });

            modelBuilder.Entity("Wasla.Domain.Doctors.DoctorSpecializationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentRevisionNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReviewedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReviewedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("SubmittedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SubmittedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId")
                        .IsUnique()
                        .HasDatabaseName("UX_DoctorSpecializationRequests_OneOpenPerDoctor")
                        .HasFilter("[Status] IN (1, 2)");

                    b.HasIndex("ReviewedByApplicationUserId");

                    b.HasIndex("SubmittedByApplicationUserId");

                    b.HasIndex("Status", "Type", "SubmittedOnUtc")
                        .HasDatabaseName("IX_DoctorSpecializationRequests_ReviewQueue");

                    b.ToTable("DoctorSpecializationRequests", (string)null);
                });

            modelBuilder.Entity("Wasla.Domain.Doctors.DoctorSpecializationRequestHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<Guid>("DoctorSpecializationRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("PerformedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PerformedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PreviousRevisionNumber")
                        .HasColumnType("int");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PerformedByApplicationUserId");

                    b.HasIndex("DoctorSpecializationRequestId", "PerformedOnUtc")
                        .HasDatabaseName("IX_DoctorSpecializationRequestHistories_RequestId_PerformedOnUtc");

                    b.ToTable("DoctorSpecializationRequestHistories", (string)null);
                });

            modelBuilder.Entity("Wasla.Domain.Doctors.DoctorSpecializationRequestItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<Guid>("MedicalSpecializationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RevisionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MedicalSpecializationId");

                    b.HasIndex("RevisionId")
                        .IsUnique()
                        .HasDatabaseName("UX_DoctorSpecializationRequestItems_OnePrimaryPerRevision")
                        .HasFilter("[IsPrimary] = 1");

                    b.HasIndex("RevisionId", "MedicalSpecializationId")
                        .IsUnique()
                        .HasDatabaseName("UX_DoctorSpecializationRequestItems_RevisionId_MedicalSpecializationId");

                    b.ToTable("DoctorSpecializationRequestItems", (string)null);
                });

            modelBuilder.Entity("Wasla.Domain.Doctors.DoctorSpecializationRequestRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DoctorSpecializationRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("SubmittedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SubmittedOnUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SubmittedByApplicationUserId");

                    b.HasIndex("DoctorSpecializationRequestId", "RevisionNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_DoctorSpecializationRequestRevisions_RequestId_RevisionNumber");

                    b.ToTable("DoctorSpecializationRequestRevisions", (string)null);
                });

            modelBuilder.Entity("Wasla.Domain.Doctors.DoctorStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("FromStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("PerformedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ToStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PerformedByApplicationUserId");

                    b.HasIndex("DoctorId", "OccurredOnUtc")
                        .HasDatabaseName("IX_DoctorStatusHistories_DoctorId_OccurredOnUtc");

                    b.ToTable("DoctorStatusHistories", (string)null);
                });

            modelBuilder.Entity("Wasla.Domain.Patients.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PersonalIdBackMediaKey")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PersonalIdFrontMediaKey")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ProfileImageMediaKey")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique()
                        .HasDatabaseName("UX_Patients_ApplicationUserId");

                    b.ToTable("Patients", (string)null);
                });

            modelBuilder.Entity("Wasla.Domain.ReferenceData.Area", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NameEn")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("CityId")
                        .HasDatabaseName("IX_Areas_CityId");

                    b.HasIndex("CityId", "NameAr")
                        .IsUnique()
                        .HasDatabaseName("UX_Areas_CityId_NameAr");

                    b.HasIndex("CityId", "NameEn")
                        .IsUnique()
                        .HasDatabaseName("UX_Areas_CityId_NameEn")
                        .HasFilter("[NameEn] IS NOT NULL");

                    b.HasIndex("CityId", "IsActive", "DisplayOrder")
                        .HasDatabaseName("IX_Areas_CityId_IsActive_DisplayOrder");

                    b.ToTable("Areas", (string)null);
                });

            modelBuilder.Entity("Wasla.Domain.ReferenceData.City", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("GovernorateId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NameEn")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("GovernorateId")
                        .HasDatabaseName("IX_Cities_GovernorateId");

                    b.HasIndex("GovernorateId", "NameAr")
                        .IsUnique()
                        .HasDatabaseName("UX_Cities_GovernorateId_NameAr");

                    b.HasIndex("GovernorateId", "NameEn")
                        .IsUnique()
                        .HasDatabaseName("UX_Cities_GovernorateId_NameEn")
                        .HasFilter("[NameEn] IS NOT NULL");

                    b.HasIndex("GovernorateId", "IsActive", "DisplayOrder")
                        .HasDatabaseName("IX_Cities_GovernorateId_IsActive_DisplayOrder");

                    b.ToTable("Cities", (string)null);
                });

            modelBuilder.Entity("Wasla.Domain.ReferenceData.Governorate", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NameEn")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("NameAr")
                        .IsUnique()
                        .HasDatabaseName("UX_Governorates_NameAr");

                    b.HasIndex("NameEn")
                        .IsUnique()
                        .HasDatabaseName("UX_Governorates_NameEn")
                        .HasFilter("[NameEn] IS NOT NULL");

                    b.HasIndex("IsActive", "DisplayOrder")
                        .HasDatabaseName("IX_Governorates_IsActive_DisplayOrder");

                    b.ToTable("Governorates", (string)null);
                });

            modelBuilder.Entity("Wasla.Domain.ReferenceData.MedicalSpecialization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionAr")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DescriptionEn")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("RestoredByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RestoredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("CreatedByApplicationUserId");

                    b.HasIndex("DeletedByApplicationUserId");

                    b.HasIndex("ModifiedByApplicationUserId");

                    b.HasIndex("NameAr")
                        .IsUnique()
                        .HasDatabaseName("UX_MedicalSpecializations_NameAr");

                    b.HasIndex("NameEn")
                        .IsUnique()
                        .HasDatabaseName("UX_MedicalSpecializations_NameEn")
                        .HasFilter("[NameEn] IS NOT NULL");

                    b.HasIndex("RestoredByApplicationUserId");

                    b.HasIndex("IsActive", "SortOrder")
                        .HasDatabaseName("IX_MedicalSpecializations_IsActive_SortOrder");

                    b.ToTable("MedicalSpecializations", (string)null);
                });

            modelBuilder.Entity("Wasla.Domain.Security.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFirstLogin")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PasswordChangedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByApplicationUserId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_ApplicationUsers_Email");

                    b.HasIndex("PhoneNumber")
                        .HasDatabaseName("IX_ApplicationUsers_PhoneNumber");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("UX_ApplicationUsers_UserName");

                    b.ToTable("ApplicationUsers", (string)null);
                });

            modelBuilder.Entity("Wasla.Domain.Security.PasswordResetChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ConsumedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("FailedAttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InvalidatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("OtpHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("ResetTokenExpiresOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResetTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("VerifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique()
                        .HasDatabaseName("UX_PasswordResetChallenges_Current_ApplicationUserId")
                        .HasFilter("[InvalidatedOnUtc] IS NULL AND [ConsumedOnUtc] IS NULL");

                    b.HasIndex("ExpiresOnUtc")
                        .HasDatabaseName("IX_PasswordResetChallenges_ExpiresOnUtc");

                    b.HasIndex("ApplicationUserId", "CreatedOnUtc")
                        .HasDatabaseName("IX_PasswordResetChallenges_ApplicationUserId_CreatedOnUtc");

                    b.ToTable("PasswordResetChallenges", (string)null);
                });

            modelBuilder.Entity("Wasla.Domain.Security.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSystemPermission")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByApplicationUserId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Permissions_Name");

                    b.ToTable("Permissions", (string)null);
                });

            modelBuilder.Entity("Wasla.Domain.Security.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByApplicationUserId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Roles_Name");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Wasla.Domain.Security.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByApplicationUserId");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("IX_RolePermissions_PermissionId");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_RolePermissions_RoleId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique()
                        .HasDatabaseName("UX_RolePermissions_RoleId_PermissionId");

                    b.ToTable("RolePermissions", (string)null);
                });

            modelBuilder.Entity("Wasla.Domain.Security.SuperAdmin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRootSuperAdmin")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("RestoredOnUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique()
                        .HasDatabaseName("UX_SuperAdmins_ApplicationUserId");

                    b.HasIndex("CreatedByApplicationUserId");

                    b.HasIndex("IsRootSuperAdmin")
                        .IsUnique()
                        .HasDatabaseName("UX_SuperAdmins_OneRoot")
                        .HasFilter("[IsRootSuperAdmin] = 1");

                    b.ToTable("SuperAdmins", (string)null);
                });

            modelBuilder.Entity("Wasla.Domain.Security.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .HasDatabaseName("IX_UserRoles_ApplicationUserId");

                    b.HasIndex("CreatedByApplicationUserId");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_UserRoles_RoleId");

                    b.HasIndex("ApplicationUserId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("UX_UserRoles_ApplicationUserId_RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Wasla.Infrastructure.EntityFrameworkCore.SqlServer.Email.EmailOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("HtmlBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("NextAttemptOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ProcessingToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TextBody")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedOnUtc")
                        .HasDatabaseName("IX_EmailOutboxMessages_CreatedOnUtc");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UX_EmailOutboxMessages_IdempotencyKey");

                    b.HasIndex("Status", "NextAttemptOnUtc")
                        .HasDatabaseName("IX_EmailOutboxMessages_Status_NextAttemptOnUtc");

                    b.ToTable("EmailOutboxMessages", (string)null);
                });

            modelBuilder.Entity("Wasla.Domain.Doctors.Doctor", b =>
                {
                    b.HasOne("Wasla.Domain.Security.ApplicationUser", "ApplicationUser")
                        .WithOne()
                        .HasForeignKey("Wasla.Domain.Doctors.Doctor", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wasla.Domain.Security.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ApprovedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Wasla.Domain.Security.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ReactivatedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Wasla.Domain.Security.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("RejectedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Wasla.Domain.Security.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("SuspendedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Wasla.Domain.Doctors.DoctorPracticeLocation", b =>
                {
                    b.HasOne("Wasla.Domain.ReferenceData.Area", null)
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wasla.Domain.ReferenceData.City", null)
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wasla.Domain.Doctors.Doctor", null)
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wasla.Domain.ReferenceData.Governorate", null)
                        .WithMany()
                        .HasForeignKey("GovernorateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Wasla.Domain.Doctors.DoctorSpecialization", b =>
                {
                    b.HasOne("Wasla.Domain.Security.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wasla.Domain.Doctors.Doctor", null)
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wasla.Domain.ReferenceData.MedicalSpecialization", null)
                        .WithMany()
                        .HasForeignKey("MedicalSpecializationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Wasla.Domain.Doctors.DoctorSpecializationRequest", b =>
                {
                    b.HasOne("Wasla.Domain.Doctors.Doctor", null)
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wasla.Domain.Security.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ReviewedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Wasla.Domain.Security.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("SubmittedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Wasla.Domain.Doctors.DoctorSpecializationRequestHistory", b =>
                {
                    b.HasOne("Wasla.Domain.Doctors.DoctorSpecializationRequest", null)
                        .WithMany()
                        .HasForeignKey("DoctorSpecializationRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wasla.Domain.Security.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("PerformedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Wasla.Domain.Doctors.DoctorSpecializationRequestItem", b =>
                {
                    b.HasOne("Wasla.Domain.ReferenceData.MedicalSpecialization", null)
                        .WithMany()
                        .HasForeignKey("MedicalSpecializationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wasla.Domain.Doctors.DoctorSpecializationRequestRevision", null)
                        .WithMany()
                        .HasForeignKey("RevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Wasla.Domain.Doctors.DoctorSpecializationRequestRevision", b =>
                {
                    b.HasOne("Wasla.Domain.Doctors.DoctorSpecializationRequest", null)
                        .WithMany()
                        .HasForeignKey("DoctorSpecializationRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wasla.Domain.Security.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("SubmittedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Wasla.Domain.Doctors.DoctorStatusHistory", b =>
                {
                    b.HasOne("Wasla.Domain.Doctors.Doctor", null)
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wasla.Domain.Security.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("PerformedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Wasla.Domain.Patients.Patient", b =>
                {
                    b.HasOne("Wasla.Domain.Security.ApplicationUser", "ApplicationUser")
                        .WithOne()
                        .HasForeignKey("Wasla.Domain.Patients.Patient", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Wasla.Domain.ReferenceData.Area", b =>
                {
                    b.HasOne("Wasla.Domain.ReferenceData.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Wasla.Domain.ReferenceData.City", b =>
                {
                    b.HasOne("Wasla.Domain.ReferenceData.Governorate", "Governorate")
                        .WithMany()
                        .HasForeignKey("GovernorateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Governorate");
                });

            modelBuilder.Entity("Wasla.Domain.ReferenceData.MedicalSpecialization", b =>
                {
                    b.HasOne("Wasla.Domain.Security.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wasla.Domain.Security.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("DeletedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Wasla.Domain.Security.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ModifiedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Wasla.Domain.Security.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("RestoredByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Wasla.Domain.Security.ApplicationUser", b =>
                {
                    b.HasOne("Wasla.Domain.Security.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Wasla.Domain.Security.PasswordResetChallenge", b =>
                {
                    b.HasOne("Wasla.Domain.Security.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Wasla.Domain.Security.Permission", b =>
                {
                    b.HasOne("Wasla.Domain.Security.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Wasla.Domain.Security.Role", b =>
                {
                    b.HasOne("Wasla.Domain.Security.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Wasla.Domain.Security.RolePermission", b =>
                {
                    b.HasOne("Wasla.Domain.Security.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Wasla.Domain.Security.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wasla.Domain.Security.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Wasla.Domain.Security.SuperAdmin", b =>
                {
                    b.HasOne("Wasla.Domain.Security.ApplicationUser", "ApplicationUser")
                        .WithOne()
                        .HasForeignKey("Wasla.Domain.Security.SuperAdmin", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wasla.Domain.Security.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Wasla.Domain.Security.UserRole", b =>
                {
                    b.HasOne("Wasla.Domain.Security.ApplicationUser", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wasla.Domain.Security.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Wasla.Domain.Security.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Wasla.Domain.Security.ApplicationUser", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
